version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    command: npm run start
    image: leadsbuffet-client
    container_name: leadsbuffet-client-container
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
    networks:
      - leadsbuffet-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm run start:dev
    image: leadsbuffet-server
    container_name: leadsbuffet-server-container
    depends_on:
      - db
      - dynamodb
    volumes:
      - ./server:/usr/src/app
    networks:
      - leadsbuffet-network

  db:
    image: mysql
    container_name: leadsbuffet-db-container
    restart: always
    environment:
      MYSQL_DATABASE: leadsbuffet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - leadsbuffet-network
    volumes:
      - leadsbuffet-volume:/data/db

  dynamodb:
    image: amazon/dynamodb-local
    container_name: leadsbuffet-dynamodb-container
    ports:
      - "8000:8000"
    networks:
      - leadsbuffet-network
    volumes:
      - leadsbuffet-volume:/data/db

  nginx:
    image: nginx
    container_name: leadsbuffet-nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

    depends_on:
      - client
      - server
    networks:
      - leadsbuffet-network

networks:
  leadsbuffet-network:
    driver: bridge

volumes:
  leadsbuffet-volume:
